### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by oreophilum** [blueprint-freespeech/gosling#1]
Hi, first: thanks for this awesome library. I'm wondering if you consider publishing `gosling` to [crates.io](https://crates.io)? That would integrate it better into the rust ecosystem and make linking from rust easier.

~~And choosing a foss license would be awesome.~~

~~Some datapoints:~~
* ~~Arti: [MIT or Apache2](https://gitlab.torproject.org/tpo/core/arti#license)~~
* ~~Tor: [BSD 3-clause license](https://gitlab.torproject.org/tpo/core/tor/-/blob/main/LICENSE)~~
* ~~SecureDrop: [AGPL 3.0](https://github.com/freedomofpress/securedrop/blob/develop/LICENSE)~~

~~I think most prominent in the tor community is the BSD 3-clause license, probably because tor itself is licensed with it. For applications sometimes GPL or BSD 3-clause is chosen. I personally prefer some kind of copyleft like [LGPL-3.0-only](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) or [MPL-2.0](https://en.wikipedia.org/wiki/Mozilla_Public_License) for libraries. But it is all up to you to decide :).~~

*Edit: Moved the choosing a foss license to #3*

**Comment by pospeselr** [comment]
We'll cross this bridge once we have something to publish (hopefully middle of 2022)

**Comment by pospeselr** [comment]
Duped of #69
