### ISSUE TITLE
Async TCP Stream using bundled legacy tor provider

### ISSUE THREAD

**Issue by tr0gi** [blueprint-freespeech/gosling#129]
I want to know if it's possible to connect to a .onion server using the bundled c-tor.
Ideally I need to know if it's possible to create the TCP listener/server using the bundled-c tor provider as well.

Essentially, I want to have a TCP server which listens on a .onion, port 420 for example, and I want to have multiple clients be able to connect to it.

Would I be better off using arti-client-tor-client?

It's also worth noting that I want to make the client reconnect using pluggable transports if connection fails after a few tries.

I really seem not to understand how you create a hidden-service, and have a TCP listener on it as well, it's kind of confusing.

**Comment by tr0gi** [comment]
Just found basic_onion_service_test. Perhaps it'd be better in my case to use arti-client-tor-client on the server-side and a bundled c-tor on the client side?

**Comment by morganava** [comment]
You can indeed programmatically host an onion-service using the tor-interface crate, and there are various tests in [tests/tor_provider.rs](https://github.com/blueprint-freespeech/gosling/blob/main/source/gosling/crates/tor-interface/tests/tor_provider.rs) which demonstrate how. The relevant method is https://docs.rs/tor-interface/0.5.0/tor_interface/tor_provider/trait.TorProvider.html#tymethod.listener

The `arti-client-tor-client` feature and ArtiClientTorClient implementation are experimental, so all of the warnings/caveats found on https://crates.io/crates/arti-client apply.

And a final note, the TorProvider interface is not exposed through the cgosling FFI, so you will have to use the tor-interface crate directly through Rust to use this funcitonality.

**Comment by tr0gi** [comment]
Got it.
I'm using tor-interface with arti-client-tor-client.

It would seem like OnionStream doesn't implement AsyncRead/Write. Is this intentional?

**Comment by tr0gi** [comment]
Alright, looking at the comments :
> A wrapper around a [std::net::TcpListener] with some Tor-specific customisations.

An onion-listener can be constructed using the [TorProvider::listener] method.

My server-side uses Tokio TcpListener, how would you recommend I proceed?

**Comment by morganava** [comment]
I would create a thread/task which repeatedly calls TorProvider::listener() which takes the received OnionStream, converts to a std::TcpStream ( https://docs.rs/tor-interface/0.5.0/tor_interface/tor_provider/struct.OnionStream.html#impl-From%3COnionStream%3E-for-TcpStream ), and then from that build an async tokio::TcpStream ( https://docs.rs/tokio/1.41.1/tokio/net/struct.TcpStream.html#method.from_std )

**Comment by morganava** [comment]
@tr0gi any luck?

**Comment by tr0gi** [comment]
Yeah I just made everything async xd
