### ISSUE TITLE
Fix all clippy warnings

### ISSUE THREAD

**Issue by nmathewson** [blueprint-freespeech/gosling#22]
Clippy is the standard Rust linter that can tell you about all kinds of problems and style issues in your code.  Just run "cargo clippy" to see the list of complaints.

**Comment by pospeselr** [comment]
Fixed in c77f8ccc8920ac273a2eec54a84290fa41537891 and 'lint' make target added in 580a28f2a7e61288a70e77d870c484e6b913a271 which invokes cargo clippy and cppcheck.
