### ISSUE TITLE
Replace most of work_manager with crossbeam_channel or crossbeam_queue

### ISSUE THREAD

**Issue by nmathewson** [blueprint-freespeech/gosling#27]
`crossbeam_channel` and `crossbeam_queue` are well regarded, widely used rust packages that safely implement MPMC queues.  I'd suggest using them instead of building your own.

**Comment by nmathewson** [comment]
Actually, `threadpool` might be the right choice here.

**Comment by pospeselr** [comment]
work_manager ended up not being necessary at all, and the tor daemon stdout reading task has just been moved to its own thread:

- stdout thread: https://github.com/blueprint-freespeech/gosling/commit/d806b503fa118eca4244ee410a9fcc2308c6ef2a
- goodbye work_manager: https://github.com/blueprint-freespeech/gosling/commit/66d24e4e3cb50f4555d05c8d394a3df19caf9a8c
