### ISSUE TITLE
Choosing a foss license

### ISSUE THREAD

**Issue by oreophilum** [blueprint-freespeech/gosling#3]
I'll split this part from #1, because it is unrelated to crates.io, but very important nonetheless. I would like to depend on this library in the future, so would be really glad if you could clarify under which license you'll provide this library. It being a foss license is a crucial requirement for me. Sorry for bothering you with another issue and thanks for taking the time to develop this library. 

*copied from #1:*

> Some datapoints.torproject.org/tpo/core/arti#license)
> * Tor: [BSD 3-clause license](https://gitlab.torproject.org/tpo/core/tor/-/blob/main/LICENSE)
> * SecureDrop: [AGPL 3.0](https://github.com/freedomofpress/securedrop/blob/develop/LICENSE)
> 
> I think most prominent in the tor community is the BSD 3-clause license, probably because tor itself is licensed with it. For applications sometimes GPL or BSD 3-clause is chosen. I personally prefer some kind of copyleft like [LGPL-3.0-only](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) or [MPL-2.0](https://en.wikipedia.org/wiki/Mozilla_Public_License) for libraries. But it is all up to you to decide :).

Resources which might help as well:
* https://choosealicense.com/
* https://www.gnu.org/licenses/license-recommendations.html
* https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by pospeselr** [comment]
Went for simplified BSD with commons clause preamble

**Comment by oreophilum** [comment]
Thanks for clarifying and sorry for nagging again: fyi, commons clause makes the license proprietary/open core. It's not a foss license. Some reading material with further links:
* https://fedoraproject.org/wiki/Licensing/CommonsClause
* https://www.gnu.org/licenses/license-list.html#comclause
