### ISSUE TITLE
Write a usage guide and associated toy 'hello world' example projects

### ISSUE THREAD

**Issue by morganava** [blueprint-freespeech/gosling#76]
The example project should just be a simple 'echo' server using gosling (in Rust) and cgosling (in C++).

- [x] Rust
- [x] C++

The example projects should have a Gosling usage guide that explains the relevant components, project layout, etc.

**Comment by pospeselr** [comment]
C++ example project done in 23925dbc098d3097a4527bfdba4311a2a400692e

**Comment by morganava** [comment]
Rust example project done in 1da9e7dd8fd6f187cf4ac84194d72b1d55c1dfd6

**Comment by morganava** [comment]
Need to write READMEs for each project with a little walk-through of each application.

**Comment by morganava** [comment]
Example chat application readmes completed in dd73c05d66ac5767dbe946287a081ef86a36abb9

Usage guide added in c4629eafd6d739762594f122794a1a8e42861b0b
