### ISSUE TITLE
Integrate arti-client Rust crate into build and Implement ArtiClient stubs

### ISSUE THREAD

**Issue by morganava** [blueprint-freespeech/gosling#93]
arti-client crate: https://crates.io/crates/arti-client

Required TorProvider features:

- [x] bootstrapping
- [x] client onion service connectivity
- [x] client onion service connectivity with onion authorization support
- [x] hosting onion service
- [x] hosting onion service with onion authorization support

**Comment by pospeselr** [comment]
a full implementation is blocked until upstream implements onion authorization support

**Comment by morganava** [comment]
last required feature implemented in b8c0e3ec88d89ecf9602db8a8f3a8c7f1f95633f
